spring:
  application:
    name: GuildaProject

  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true

  logging:
    level:
      org.hibernate.tool.schema: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.orm.jpa: DEBUG

  profiles:
    active: dev